name: validate-install-from-source

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: ${{matrix.vector.image}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vector:
        - image: ubuntu
        - image: debian
        - image: linuxmintd/mint20-amd64
        - image: fedora
        - image: centos
        - image: redhat/ubi8
        - image: alpine
    container: ${{matrix.vector.image}}
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [ ${{matrix.vector.image}} == "centos" ]; then
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
          fi

          sh "${GITHUB_WORKSPACE}/src/linux/Packaging.Linux/install-from-source.sh" -y
          git-credential-manager-core --help || exit 1